openapi: 3.0.0
info:
  title: Chatwoot Webhook API
  description: API that handles incoming webhooks from Chatwoot.
  version: 1.0.0
servers:
  - url: https://chatwoot-jwcv.onrender.com
    description: Production server
paths:
  /chatwoot-webhook:
    post:
      summary: Handle Chatwoot webhook
      operationId: handleWebhook
      requestBody:
        description: The data sent by Chatwoot in the webhook
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: The message content sent by the user via Chatwoot
                conversation:
                  type: object
                  description: The conversation details
                  properties:
                    id:
                      type: integer
                      description: The ID of the conversation
              required:
                - content
                - conversation
      responses:
        '200':
          description: Webhook received and processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  content:
                    type: string
                    description: The fixed response content from the webhook
                    example: Lxme trading
        '400':
          description: Invalid request data
